QSPIF Flash Block Device example
ARMmbed/mbed-os-example-blockdevice-qspif pull request #1
Opened 2018-08-08 12:51 UTC by offirko

2018-08-08 12:53 UTC, offirko commented
Hello: @bulislaw , @donatieng , @ARMmbed/mbed-os-maintainers , @dannybenor , @davidsaada .
I'd appreciate your review of the QSPIF Block Device Example

2018-08-09 08:49 UTC, 0xc0170 commented
Can we rename this repo, as other examples, this should be `mbed-os-example-qspif-blockdevice` or rather qspif as the last word? As we have mbed-os-example-blockdevice, I would assume adding suffix here would identify what blockdevice it is.

2018-08-09 09:36 UTC, offirko commented
@0xc0170 - renamed both and made the adjustments, thanks

2018-08-15 15:36 UTC, davidsaada requested changes
Looks good to me, beside a few petty issue.

2018-08-15 15:36 UTC, davidsaada commented on main.cpp
> +#include "mbed.h"
Can we do without this include?

2018-08-15 15:36 UTC, davidsaada commented on main.cpp
> +    printf("QSPI SFDP Flash Block Device example\n");
Better to have stdio.h included if you use this.

2018-08-23 09:28 UTC, offirko commented on main.cpp
> +#include "mbed.h"
removed

2018-08-23 09:29 UTC, merged